/**
 * This file was generated by the JPA Modeler
 */
package com.eshop.cart.model;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.ws.rs.FormParam;

/**
 * @author gmendoza
 */
@Entity
public class Cliente implements Serializable {

    @Id
    //@GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("id")
    private Long id;

    @Basic
    @FormParam("nombres")
    private String nombres;

    @Basic
    @FormParam("apellidos")
    private String apellidos;

    @Basic
    @FormParam("edad")
    private String edad;

    @Basic
    @FormParam("direccion")
    private String direccion;

    @Basic
    @FormParam("celular")
    private String celular;

    @OneToMany(targetEntity = ProductoOrden.class)
    private List<ProductoOrden> productoOrdens;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getEdad() {
        return this.edad;
    }

    public void setEdad(String edad) {
        this.edad = edad;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public List<ProductoOrden> getProductoOrdens() {
        return this.productoOrdens;
    }

    public void setProductoOrdens(List<ProductoOrden> productoOrdens) {
        this.productoOrdens = productoOrdens;
    }

}
