/**
 * This file was generated by the JPA Modeler
 */
package com.eshop.cart.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.ws.rs.FormParam;

/**
 * @author gmendoza
 */
@Entity
public class ProductoOrden implements Serializable {

    @Id
   // @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("id")
    private Long id;

    @Basic
    @FormParam("cantidad")
    private String cantidad;

    @Basic
    @FormParam("localizacion")
    private String localizacion;

    @Basic
    @FormParam("tiempo")
    private String tiempo;

    @Basic
    @FormParam("promocion")
    private String promocion;

    @ManyToOne(targetEntity = Producto.class)
    private Producto producto;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

    public String getLocalizacion() {
        return this.localizacion;
    }

    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }

    public String getTiempo() {
        return this.tiempo;
    }

    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }

    public String getPromocion() {
        return this.promocion;
    }

    public void setPromocion(String promocion) {
        this.promocion = promocion;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

}
