/**
 * This file was generated by the JPA Modeler
 */
package com.eshop.cart.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.ws.rs.FormParam;

/**
 * @author gmendoza
 */
@Entity
public class Producto implements Serializable {

    @Id
   // @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("id")
    private Long id;

    @Basic
    @FormParam("nombre")
    private String nombre;

    @Basic
    @FormParam("descripcion")
    private String descripcion;

    @Basic
    @FormParam("listaPrecio")
    private String listaPrecio;

    @Basic
    @FormParam("ventaPrecio")
    private String ventaPrecio;

    @Basic
    @FormParam("especPrecio")
    private String especPrecio;

    @Basic
    @FormParam("envioGratis")
    private String envioGratis;

    @Basic
    @FormParam("cantidad")
    private String cantidad;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getListaPrecio() {
        return this.listaPrecio;
    }

    public void setListaPrecio(String listaPrecio) {
        this.listaPrecio = listaPrecio;
    }

    public String getVentaPrecio() {
        return this.ventaPrecio;
    }

    public void setVentaPrecio(String ventaPrecio) {
        this.ventaPrecio = ventaPrecio;
    }

    public String getEspecPrecio() {
        return this.especPrecio;
    }

    public void setEspecPrecio(String especPrecio) {
        this.especPrecio = especPrecio;
    }

    public String getEnvioGratis() {
        return this.envioGratis;
    }

    public void setEnvioGratis(String envioGratis) {
        this.envioGratis = envioGratis;
    }

    public String getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

}
